### ISSUE TITLE
Add ability to output the `presentation` value of a file entity by providing its `slug` in the request

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Cms#2]
Sample use case: CSS link tag
`<link rel="stylesheet" href="{{cms}}{{environment}}/files/{{file-slug}}">`

This will require knowing the mime type of the file.

**Comment by StephenOTT** [comment]
Looking at the sample payload from the CMS postman examples, mime type appears to be a missing field and a oversight.  mime type should be added as a field when POST /files

**Comment by StephenOTT** [comment]
Related issue for adding Mime Type: #3

**Comment by StephenOTT** [comment]
@baddlan  can you give a example of a file tag?

**Comment by baddlan** [comment]
Sorry, by file `tag` I meant `slug`.
I'll update the title and description of the issue.

**Comment by mario-digitalstate** [comment]
Done.
