### ISSUE TITLE
Unable to create a Page entity due to `slug` validation error

### ISSUE THREAD

**Issue by baddlan** [DigitalState/Cms#4]
`”slug: This value should not be blank.”` error is thrown whether `slug` is provided **or** not.

**Comment by StephenOTT** [comment]
Should slug be a required field @baddlan ?

**Comment by baddlan** [comment]
It depends on what you want to do with pages.
But this bug prevents the Page from being saved whether `slug` is provided or not.

**Comment by StephenOTT** [comment]
@baddlan ahh! I did not see the previous "or".  Updated with bold.

**Comment by mario-digitalstate** [comment]
Sluggable interface was missing. Fixed.
